#!/usr/bin/env ruby

# Download iPlayer programmes by spoofing an iPhone
# Paul Battley - http://po-ru.com/
#
# Get the latest version via subversion:
# svn co http://paulbattley.googlecode.com/svn/iplayer-dl

require 'iplayer'
require 'optparse'
require 'wx'

include IPlayer
include IPlayer::Errors

OPTIONS = {
  :type_preference  => %w[original signed],
  :download_path    => Dir.pwd,
  :http_proxy       => ENV['http_proxy']
}

class SelectFrame < Wx::Frame
  def initialize
    super(nil, -1, "iPandora")

    if http_proxy = OPTIONS[:http_proxy]
      http_proxy = 'http://' + http_proxy unless http_proxy =~ %r{^http://}
      u = URI.parse(http_proxy)
      http = Net::HTTP::Proxy(u.host, u.port)
    else
      http = Net::HTTP
    end
    @browser = Browser.new(http)

    @pid_label = Wx::StaticText.new(self, -1, "Programme ID")
    @pid_field = Wx::TextCtrl.new(self, -1, "", Wx::DEFAULT_POSITION, Wx::Size.new(200,24))
    @download_progress = Wx::Gauge.new(self, -1, 1)
    @cancel_button = Wx::Button.new(self, -1, "Cancel")
    @download_button = Wx::Button.new(self, -1, "Download")
    @status_bar = Wx::StatusBar.new(self, -1)
    @status_bar.set_status_text("Waiting")
    set_status_bar(@status_bar)

    evt_button(@cancel_button.get_id){ |e| cancel_button_clicked(e)   }
    evt_button(@download_button.get_id){ |e| download_button_clicked(e) }

    do_layout
  end

  def do_layout
    sizer_main = Wx::BoxSizer.new(Wx::VERTICAL)
    sizer_buttons = Wx::BoxSizer.new(Wx::HORIZONTAL)
    sizer_input = Wx::BoxSizer.new(Wx::HORIZONTAL)
    sizer_input.add(@pid_label, 0, Wx::ALL|Wx::ALIGN_CENTER_VERTICAL, 4)
    sizer_input.add(@pid_field, 0, Wx::ALL|Wx::EXPAND|Wx::ALIGN_CENTER_VERTICAL, 4)
    sizer_main.add(sizer_input, 0, Wx::EXPAND, 0)
    sizer_main.add(@download_progress, 0, Wx::ALL|Wx::EXPAND, 4)
    sizer_buttons.add(@cancel_button, 0, Wx::ALL, 4)
    sizer_buttons.add(@download_button, 0, Wx::ALL, 4)
    sizer_main.add(sizer_buttons, 0, Wx::ALIGN_RIGHT|Wx::ALIGN_CENTER_HORIZONTAL, 0)
    self.set_sizer(sizer_main)
    sizer_main.fit(self)
    layout
    centre
  end

  def cancel_button_clicked(event)
    destroy
  end

  def download_button_clicked(event)
    pid = @pid_field.get_value
    if pid.empty?
      message_box('You must specify a programme ID before I can download it.')
      return
    end

    if pid =~ %r!/item/([a-z0-9]{8})!
      pid = $1
    end
    begin
      title = Metadata.new(pid, @browser).full_title
    rescue MetadataError
      title = pid
    end
    filename = "#{ title }.mov".gsub(/[^a-z0-9 \-\.]+/i, '')
    fd = Wx::FileDialog.new(nil, 'Save as', '', filename, 'iPlayer Movies (*.mov)|*.mov', Wx::FD_SAVE)
    case fd.show_modal
    when Wx::ID_OK
      path = fd.get_path

      downloader = Downloader.new(@browser, pid)
      available_versions = downloader.available_versions
      raise MP4Unavailable if available_versions.empty?
      version = available_versions.sort_by{ |v| 
        OPTIONS[:type_preference].index(v.name) || 100 
      }.first

      if File.exist?(path)
        offset = File.size(path)
      else
        offset = 0
      end
      @status_bar.set_status_text("Downloading #{File.basename(path)}")
      $app.yield

      File.open(path, 'a+b') do |io|
        downloader.download(version.pid, io, offset) do |position, max|
          @download_progress.set_range(max)
          @download_progress.set_value(position)
          $app.yield
        end
      end
      
    else
    end
  end

  def message_box(message, options={})
    options = {:title => 'iPandora', :buttons => Wx::OK}.merge(options)
    Wx::MessageDialog.new(self, message, options[:title], options[:buttons]).show_modal
  end
end

class App < Wx::App
  def on_init
    SelectFrame.new.show()
  end
end

$app = App.new
$app.main_loop
