#!/usr/bin/env ruby

# Download iPlayer programmes by spoofing an iPhone
# WxWidgets GUI interface
# Paul Battley - http://po-ru.com/
#
# Get the latest version via subversion:
# svn co http://paulbattley.googlecode.com/svn/iplayer-dl

$:.unshift(File.expand_path(File.join(File.dirname(__FILE__), '..', 'lib')))
require 'iplayer'
require 'iplayer/gui/app'
require 'iplayer/gui/main_frame'

OPTIONS = {
  :type_preference  => %w[original signed],
  :http_proxy       => ENV['http_proxy']
}

IPlayer::GUI::App.new(IPlayer::GUI::MainFrame, OPTIONS).main_loop
